src/Entity/Auteur.php
<?php

namespace App\Entity;

use App\Repository\AuteurRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: AuteurRepository::class)]
class Auteur
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $nom_prenom;

    #[ORM\Column(type: 'string', length: 1)]
    private $sexe;

    #[ORM\Column(type: 'string', length: 255)]
    private $nationalite;

    #[ORM\Column(type: 'date')]
    private $date_naissance;

    #[ORM\ManyToMany(targetEntity: Livre::class, inversedBy: 'auteurs')]
    private $livres;

    public function __construct()
    {
        $this->livres = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomPrenom(): ?string
    {
        return $this->nom_prenom;
    }

    public function setNomPrenom(string $nom_prenom): self
    {
        $this->nom_prenom = $nom_prenom;

        return $this;
    }

    public function getSexe(): ?string
    {
        return $this->sexe;
    }

    public function setSexe(string $sexe): self
    {
        $this->sexe = $sexe;

        return $this;
    }

    public function getNationalite(): ?string
    {
        return $this->nationalite;
    }

    public function setNationalite(string $nationalite): self
    {
        $this->nationalite = $nationalite;

        return $this;
    }

    public function getDateNaissance(): ?\DateTimeInterface
    {
        return $this->date_naissance;
    }

    public function setDateNaissance(\DateTimeInterface $date_naissance): self
    {
        $this->date_naissance = $date_naissance;

        return $this;
    }

    /**
     * @return Collection|Livre[]
     */
    public function getLivres(): Collection
    {
        return $this->livres;
    }

    public function addLivre(Livre $livre): self
    {
        if (!$this->livres->contains($livre)) {
            $this->livres[] = $livre;
        }

        return $this;
    }

    public function removeLivre(Livre $livre): self
    {
        $this->livres->removeElement($livre);

        return $this;
    }
}

src/Entity/Livre.php
<?php

namespace App\Entity;

use App\Repository\LivreRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: LivreRepository::class)]
class Livre
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 20)]
    private $isbn;

    #[ORM\Column(type: 'string', length: 255)]
    private $titre;

    #[ORM\Column(type: 'integer')]
    private $nombre_pages;

    #[ORM\Column(type: 'date')]
    private $date_parution;

    #[ORM\Column(type: 'integer')]
    private $note;

    #[ORM\ManyToMany(targetEntity: Auteur::class, mappedBy: 'livres')]
    private $auteurs;

    #[ORM\ManyToMany(targetEntity: Genre::class, inversedBy: 'livres')]
    private $genres;

    public function __construct()
    {
        $this->auteurs = new ArrayCollection();
        $this->genres = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIsbn(): ?string
    {
        return $this->isbn;
    }

    public function setIsbn(string $isbn): self
    {
        $this->isbn = $isbn;

        return $this;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getNombrePages(): ?int
    {
        return $this->nombre_pages;
    }

    public function setNombrePages(int $nombre_pages): self
    {
        $this->nombre_pages = $nombre_pages;

        return $this;
    }

    public function getDateParution(): ?\DateTimeInterface
    {
        return $this->date_parution;
    }

    public function setDateParution(\DateTimeInterface $date_parution): self
    {
        $this->date_parution = $date_parution;

        return $this;
    }

    public function getNote(): ?int
    {
        return $this->note;
    }

    public function setNote(int $note): self
    {
        $this->note = $note;

        return $this;
    }

    /**
     * @return Collection|Auteur[]
     */
    public function getAuteurs(): Collection
    {
        return $this->auteurs;
    }

    public function addAuteur(Auteur $auteur): self
    {
        if (!$this->auteurs->contains($auteur)) {
            $this->auteurs[] = $auteur;
            $auteur->addLivre($this);
        }

        return $this;
    }

    public function removeAuteur(Auteur $auteur): self
    {
        if ($this->auteurs->removeElement($auteur)) {
            $auteur->removeLivre($this);
        }

        return $this;
    }

    /**
     * @return Collection|Genre[]
     */
    public function getGenres(): Collection
    {
        return $this->genres;
    }

    public function addGenre(Genre $genre): self
    {
        if (!$this->genres->contains($genre)) {
            $this->genres[] = $genre;
        }

        return $this;
    }

    public function removeGenre(Genre $genre): self
    {
        $this->genres->removeElement($genre);

        return $this;
    }
}

src/Controller/BookstoreController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\Livre;
use Doctrine\Persistence\ManagerRegistry;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Doctrine\Persistence\ObjectManager;
use App\Entity\Genre;

class BookstoreController extends AbstractController
{
    #[Route('/store', name: 'store')]
    #[Route('/home', name: 'home')]
    public function index(ManagerRegistry $doctrine, Request $req, PaginatorInterface $paginator): Response
    {
        $this->denyAccessUnlessGranted('ROLE_USER');

        $repo = $doctrine->getRepository(Livre::class);
        $items = $repo->findAll();
        $livres = $paginator->paginate(
            $items,
            $req->query->getInt('page', 1),
            8
        );

        $repo = $doctrine->getRepository(Genre::class);
        $genres = $repo->findAll();

        return $this->render('bookstore/index.html.twig', [
            'controller_name' => 'BookstoreController',
            'livres' => $livres,
            'genres' => $genres
        ]);
    }

    #[Route('/bookstore', name: 'bookstore')]
    public function books(ManagerRegistry $doctrine, Request $req, PaginatorInterface $paginator) : Response
    {
        $this->denyAccessUnlessGranted('ROLE_USER');
        
        $repo = $doctrine->getRepository(Livre::class);
        $items = $repo->findAll();
        $livres = $paginator->paginate(
            $items,
            $req->query->getInt('page', 1),
            8
        );

        return $this->render('bookstore/bookstore.html.twig', [
            'controller_name' => 'BookstoreController',
            'livres' => $livres
        ]); 
    }

    #[Route('/bookstore/book/new', name: 'newBook')]
    #[Route('/bookstore/book/{id}/edit', name: 'editBook')]
    public function book(Livre $livre = null, Request $req, ObjectManager $manager)
    {
        $this->denyAccessUnlessGranted('ROLE_ADMIN');
        
        $edit = true;
        if(!$livre){
            $livre = new Livre();
            $edit = false;
        } 

        $formBook = $this->createFormBuilder($livre)
                           ->add('isbn')
                           ->add('titre')
                           ->add('NombrePages')
                           ->add('DateParution', DateType::class, [
                            'widget' => 'single_text',
                        ])
                           ->add('note')
                           ->getForm();

        $formBook->handleRequest($req);

        if($formBook->isSubmitted() && $formBook->isValid()){
            $manager->persist($livre);
            $manager->flush();

            return $this->redirectToRoute('book_show', ['id'=> $livre->getId()]);
        }


        return $this->render('bookstore/book.html.twig', [
            'formBook' => $formBook->createView(),
            'edit' => $edit
        ]);
    }

    #[Route('/book/delete/{id}', name: 'delBook')]
    public function delete(ManagerRegistry $doctrine, $id, ObjectManager $manager) : Response
    {
        $this->denyAccessUnlessGranted('ROLE_ADMIN');
        
        $repo = $doctrine->getRepository(Livre::class);
        $book = $repo->find($id);
        
        $manager->remove($book);
        $manager->flush();
        
        return $this->redirectToRoute('bookstore');

    }



    #[Route('/bookstore/book/{id}', name: 'book_show')]
    public function show(ManagerRegistry $doctrine,$id): Response
    {
        $this->denyAccessUnlessGranted('ROLE_USER');
        
        $repo = $doctrine->getRepository(Livre::class);
        $livre = $repo->find($id);
        return $this->render('bookstore/show.html.twig',[
            'livre' => $livre
        ]);
    }
}

templates/bookstore/book.html.twig
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title>
			{% block title %}Nos livres !
			{% endblock %}
		</title>
		<script type="text/javascript" src="js/jquery-1.8.0.js"></script>
		<link rel="stylesheet" href="https://bootswatch.com/5/yeti/bootstrap.min.css">
		<link
		rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>📚</text></svg>">
		{# Run `composer require symfony/webpack-encore-bundle` to start using Symfony UX #}
		{% block stylesheets %}
			{{ encore_entry_link_tags('app') }}
		{% endblock %}

		{% block javascripts %}
			{{ encore_entry_script_tags('app') }}
		{% endblock %}
	</head>
	<body>
		<nav class="navbar navbar-expand-lg navbar-light bg-light">
			<div class="container-fluid">
				<a class="navbar-brand" href="{{ path('store' )}}">MIL Store</a>
				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor03" aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>

				<div class="collapse navbar-collapse" id="navbarColor03">
					<ul class="navbar-nav me-auto justify-content-center">
						<li class="nav-item">
							<a class="nav-link" href="{{ path('store' )}}">Home
								
							</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="{{ path('auteur' )}}">Auteurs</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="{{ path('genre')}}">Genres</a>
						</li>
                        <li class="nav-item">
							<a class="nav-link active" href="{{ path('bookstore')}}">Livres
                            <span class="visually-hidden">(current)</span>
                            </a>
						</li>
						{% if is_granted('ROLE_ADMIN') %}
						<li class="nav-item">								
							<a class="nav-link btn btn-secondary" href="{{ path('newBook')}}">Nouveau livre</a>
						</li>
						{% endif %}
                        
					</ul>
				</div>
			</div>
		</nav>
		<div class="container">
			<h1>
			{% if edit %}
				Modifier le livre
			{% else %}
				Ajouter un nouveau livre
			{% endif %}
			</h1>

			{{form_start(formBook)}}

			{{form_widget(formBook)}}
			<button class="btn btn-success" type="submit">
			{% if edit %}
				Enregistrer les modifications
			{% else %}
				Ajouter le livre
			{% endif %}
			 
			</button>
			{{form_end(formBook)}}
		</div>
	</body>
</html>

templates/bookstore/bookstore.html.twig
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title>
			{% block title %}Nos livres !
			{% endblock %}
		</title>
		<script type="text/javascript" src="js/jquery-1.8.0.js"></script>
		<link rel="stylesheet" href="https://bootswatch.com/5/yeti/bootstrap.min.css">
		<link
		rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>📚</text></svg>">
		{# Run `composer require symfony/webpack-encore-bundle` to start using Symfony UX #}
		{% block stylesheets %}
			{{ encore_entry_link_tags('app') }}
		{% endblock %}

		{% block javascripts %}
			{{ encore_entry_script_tags('app') }}
		{% endblock %}
	</head>
	<body>
		<nav class="navbar navbar-expand-lg navbar-light bg-light">
			<div class="container-fluid">
				<a class="navbar-brand" href="{{ path('store' )}}">MIL Store</a>
				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor03" aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>

				<div class="collapse navbar-collapse" id="navbarColor03">
					<ul class="navbar-nav me-auto justify-content-center">
						<li class="nav-item">
							<a class="nav-link" href="{{ path('store' )}}">Home
								
							</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="{{ path('auteur' )}}">Auteurs</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="{{ path('genre')}}">Genres</a>
						</li>
                        <li class="nav-item">
							<a class="nav-link active" href="{{ path('bookstore')}}">Livres
                            <span class="visually-hidden">(current)</span>
                            </a>
						</li>
						{% if is_granted('ROLE_ADMIN') %}
						<li class="nav-item">								
							<a class="nav-link btn btn-secondary" href="{{ path('newBook')}}">Nouveau livre</a>
						</li>
						{% endif %}
					</ul>
				</div>
			</div>
		</nav>
		<div class="container">
			<div class="row">
				{% for livre in livres %}
					<div class="col-sm-6">
						<div class="card">
							<div class="card-body">
								<h5 class="card-title">{{livre.titre}}</h5>
								<h6 class="card-subtitle text-muted">{{livre.isbn}}</h6>
								<p class="card-text">Publié le
									{{livre.dateParution | date('d-m-Y')}}
									<br><small class="text-muted">Note/20 :
										{{livre.note}}</small>
								</p>
								<a href="{{ path('book_show', {'id' : livre.id} )}}" class="card-link">Afficher les détails...</a>
							</div>
							{% if is_granted('ROLE_ADMIN') %}
							<a class="btn btn-warning" href="{{ path('editBook', {'id' : livre.id})}}">Modifier</a>
							<a class="btn btn-danger" href="{{ path('delBook', {'id' : livre.id})}}">Supprimer</a>
							{% endif %}
                            
						</div>
                        
					</div>
                    
				{% endfor %}

			</div>
			<div>
				<ul class="pagination">
					{{knp_pagination_render(livres)}}
				</ul>
			</div>
		</div>
	</body>
</html>

templates/bookstore/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}MIL Bookstore
{% endblock %}

{% block body %}
	<form>
		<ul class="nav justify-content-center" style="margin : 2em;">

			<li class="nav-item">
				<select  class="form-select" name="genre" id="">
				<option selected disabled>Genre</option>
				{% for genre in genres %}
					<option>{{genre.nom}}</option>
				{% endfor %}
				</select>
			</li>
			<li class="nav-item">
				<input class="form-control" type="date" placeholder="Année de publication..." >
			</li>
			<li class="nav-item">
				<input class="form-control" type="number" placeholder="Note Livre..." min="0" max="20">
			</li>
			<li class="nav-item">
				<input class="form-control" type="text" placeholder="Auteur...">
			</li>
			<li class="nav-item">
				<button  class="btn btn-outline-info" type="submit">Filter</button>
			</li>
		</ul>

	</form>

	<div class="row">
		{% for livre in livres %}
			<div class="col-sm-6">
				<div class="card">
					<div class="card-body">
						<h5 class="card-title">{{livre.titre}}</h5>
						<h6 class="card-subtitle text-muted">{{livre.isbn}}</h6>
						<p class="card-text">Publié le
							{{livre.dateParution | date('d-m-Y')}}
							<br><small class="text-muted">Note/20 :
								{{livre.note}}</small>
						</p>
						<a href="{{ path('book_show', {'id' : livre.id} )}}" class="card-link">Afficher les détails...</a>
					</div>
				</div>
			</div>
		{% endfor %}

	</div>
	<div>
		<ul class="pagination">
			{{knp_pagination_render(livres)}}
		</ul>
	</div>
{% endblock %}

templates/bookstore/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Détails sur livre {{livre.titre}}
{% endblock %}

{% block body %}

	<div class="container">
		<h5>{{livre.titre}}
			N°
			{{livre.id}}
		</h5>
		<h6 class="text-muted">{{livre.isbn}}</h6>
		<h6 class="text-muted">Genre :
		</h6>
		<ul>
			{% for genre in livre.genres %}
				<li>
					{{genre.nom}}
				</li>
			{% endfor %}
		</ul>

		<h6 class="text-muted">Auteur :
		</h6>
		<ul>
			{% for auteur in livre.auteurs %}
				<li>
					{{auteur.nomPrenom}}
				</li>
			{% endfor %}
		</ul>
		<p>Publié le
			{{livre.dateParution | date('d-m-Y')}}
			<br><small class="text-muted">Note/20 :
				{{livre.note}}</small>
		</p>
		<hr>
		{% if is_granted('ROLE_ADMIN') %}
							<a class="btn btn-warning" href="{{ path('editBook', {'id' : livre.id})}}">Modifier</a>
							<a class="btn btn-danger" href="{{ path('delBook', {'id' : livre.id})}}">Supprimer</a>
							{% endif %}
	</div>
{% endblock %}